### ISSUE TITLE
Deel 2 van de opdracht UX vergroten is nog niet gedaan

### ISSUE THREAD

**Issue by Theo-denBlanken** [Kamil38/formulieren-test#1]
O.a. labels, required, placeholder en autofocus

**Comment by Kamil38** [comment]
Ik heb de UX gedaan maar de nummers gaan niet onder de radio buttons ik heb precies hetzelfde gedaan. Ik zelf persoonlijk denk dat het aan de fieldset ligt als het zo is kunt u mij het laten weten.

**Comment by Theo-denBlanken** [comment]
Als een element een display-type `block` heeft (krijgt), dan neemt deze de gehele beschikbare ruimte in. Dan kan er dus niets _naast_ staan. Brengt jou dat op een idee?

**Comment by Kamil38** [comment]
[cid:image002.png@01D5ADCF.04CE92A0]

Ik heb nu dit. De display type block is er maar hij doet nog steeds het zelfde
Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Theo den Blanken<mailto:notifications@github.com>
Verzonden: zondag 8 december 2019 12:04
Aan: Kamil38/formulieren-test<mailto:formulieren-test@noreply.github.com>
CC: Kamil38<mailto:bugra38@live.nl>; State change<mailto:state_change@noreply.github.com>
Onderwerp: Re: [Kamil38/formulieren-test] Deel 2 van de opdracht UX vergroten is nog niet gedaan (#1)


Als een element een display-type block heeft (krijgt), dan neemt deze de gehele beschikbare ruimte in. Dan kan er dus niets naast staan. Brengt jou dat op een idee?
