### ISSUE TITLE
Niet zo geschikte uitwerking eigen vraag

### ISSUE THREAD

**Issue by Theo-denBlanken** [Kamil38/formulieren-test#2]
```<input type="radio" name="zelf"> Nederlands <input type="radio" name="zelf"> Rekenen <input type="radio" name="zelf"> Engels <input type="radio" name="zelf"> Alle 3``` gebruikt niet de geschikte input types. Je kunt namelijk niet aangeven welke **2** vakken je favoriet zijn.

**Comment by Kamil38** [comment]
Ik heb van de radio buttons checkbox buttons gemaakt zodat je er meerdere kunt aanvinken
